{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Products available",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "queryText": "select name, price, quantity from Dvds",
       "rawQueryText": "select name, price, quantity from Dvds",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Artist available",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\n    dvds.artist AS artist_name,\n    COUNT(dvds.id) AS total_dvds\nFROM\n    dvds\nGROUP BY\n    dvds.artist\nORDER BY\n    total_dvds DESC;",
       "rawQueryText": "SELECT\n    dvds.artist AS artist_name,\n    COUNT(dvds.id) AS total_dvds\nFROM\n    dvds\nGROUP BY\n    dvds.artist\nORDER BY\n    total_dvds DESC;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Book",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Books available",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "queryText": "select name, price, quantity from Books",
       "rawQueryText": "select name, price, quantity from Books",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Books available",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\n    Books.name AS name,\n    COUNT(Books.id) AS total_Books\nFROM\n    Books\nGROUP BY\n    Books.name\nORDER BY\n    total_Books DESC;\n    ",
       "rawQueryText": "SELECT\n    Books.name AS name,\n    COUNT(Books.id) AS total_Books\nFROM\n    Books\nGROUP BY\n    Books.name\nORDER BY\n    total_Books DESC;\n    ",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Electonic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Electronics available",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "queryText": "select name, price, quantity from Electronics",
       "rawQueryText": "select name, price, quantity from Electronics",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Electronics available",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\n    Electronics.name AS name,\n    COUNT(Electronics.id) AS total_Electronics\nFROM\n    Electronics\nGROUP BY\n    Electronics.name\nORDER BY\n    total_Electronics DESC;\n    \n    ",
       "rawQueryText": "SELECT\n    Electronics.name AS name,\n    COUNT(Electronics.id) AS total_Electronics\nFROM\n    Electronics\nGROUP BY\n    Electronics.name\nORDER BY\n    total_Electronics DESC;\n    \n    ",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}